thread1:  thread1.cpp
	g++  -g  -o  thread1  thread1.cpp   -pthread  -D_REENTRANT

thread2:  thread2.cpp
	g++  -g  -o  thread2  thread2.cpp   -pthread  -D_REENTRANT

thread3:  thread3.cpp
	g++  -g  -o  thread3  thread3.cpp   -pthread  -D_REENTRANT

thread4:  thread4.cpp
	g++  -g  -o  thread4  thread4.cpp   -pthread  -D_REENTRANT

mutex:    mutex.cpp
	g++  -g  -o  mutex    mutex.cpp     -pthread  -D_REENTRANT

semphore: semphore.cpp
	g++  -g  -o  semphore semphore.cpp  -pthread  -D_REENTRANT

clean:
	rm  thread1  thread2  thread3  thread4  mutex  semphore