signal: signal.cpp
	g++  -g  -o  signal  signal.cpp

sigaction: sigaction.cpp
	g++  -g  -o  sigaction  sigaction.cpp

remove_zombie: remove_zombie.cpp
	g++  -g  -o  remove_zombie  remove_zombie.cpp


clean:
	rm  sigaction  signal  remove_zombie