eserver: echo_server.cpp
	g++  -g  -o  eserver  echo_server.cpp

eclient: echo_client.cpp
	g++  -g  -o  eclient  echo_client.cpp

mpserver: echo_mpserv.cpp
	g++  -g  -o  mpserver  echo_mpserv.cpp

clean:
	rm  eclient  eserver  mpserver