cserver:  chat_server.cpp
	g++  -g  -o  cserver  chat_server.cpp  -pthread  -D_REENTRANT

cclient:  chat_client.cpp
	g++  -g  -o  cclient  chat_client.cpp  -pthread  -D_REENTRANT

clean:   
	rm  cserver  cclient